"use client";
import React, { useState } from "react";
import { format, subDays } from "date-fns";
import {
  Select,
  SelectItem,
  SelectTrigger,
  SelectContent,
  SelectGroup,
  SelectValue,
} from "@/components/ui/select";
import { CalendarSearch } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
} from "@/components/ui/card";
import ColumnsComponent from "./columns";
import DataTableSap from "./componentes/ordensFabricoSAP/data-table";
import ColumnsComponentSap from "./componentes/ordensFabricoSAP/columns";
import ProgressoFabricoOrdensConcluidas from "./componentes/OrdensConcluidas";
import OrdensPlaneadas from "./componentes/OrdensPlaneadas";
import Retorceder from "./componentes/retorceder";
import DataTable from "./data-table";
import { FetchReatores } from "@/Services/OrdensProducao/fetchReatores";
import { FetchOrdensSAPplaneadasData } from "@/Services/OrdensProducao/fetchOrdensSAP";
import ProgressoFabricoOrdensCanceladas from "./componentes/OrdensCanceladas";
import { Button } from "@/components/ui/button";

const page = () => {
  const hoje = new Date();
  const reatores = FetchReatores();
  const diasSAP = [7, 15];
  const [dia, setDia] = useState("7");

  let ordensSAP = FetchOrdensSAPplaneadasData(
    "boposReleased",
    format(subDays(hoje, 7), "yyyy-MM-dd")
  );
  //console.log(format(hoje, "yyyy-MM-dd"));
  //const dataFetcharOrdensSAP = subDays(hoje, Number(dia));
  //console.log(dataFetcharOrdensSAP);

  return (
    <div className="flex flex-col">
      <section className="border-2 border-slate-600 rounded-md p-5 shadow-2xl items-center min-h-full justify-start m-1 max-w-full">
        <Retorceder />
        <div className="flex flex-col gap-y-3">
          <div className=" flex flex-row justify-evenly items-center mb-7">
            <OrdensPlaneadas numeroOrdensPlan={mockDAta.value.length} />
            <ProgressoFabricoOrdensConcluidas />
            <ProgressoFabricoOrdensCanceladas />
          </div>
          <div className="flex flex-row gap-4 mx-auto min-w-screen">
            <Card className="border-2 border-lime-500 flex flex-col shadow-md">
              <CardHeader>
                <CardDescription>Lista das Ordens de Fabrico</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col">
                <div className="flex flex-row place-self-end gap-x-1 items-center">
                  Obter ordens apartir últimos:
                  <div className="flex flex-col items-center gap-4">
                    <Select
                      defaultValue={"7"}
                      onValueChange={(e) => {
                        //console.log(e);

                        setDia(e);
                      }}
                    >
                      <SelectTrigger className="w-[60px]">
                        <SelectValue placeholder="Escolha um dia ..." />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectGroup>
                          {diasSAP.map((dia) => (
                            <SelectItem
                              id={dia.toString()}
                              value={dia.toString()}
                            >
                              {dia.toString()}
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                  </div>
                  dias
                  <Button
                    variant={"default"}
                    size={"icon"}
                    className="ml-2"
                    onClick={() => {
                      console.log("Apos troca de data");
                      console.log(
                        format(subDays(hoje, Number(dia)), "yyyy-MM-dd")
                      );
                      console.log("Recarregou");
                    }}
                  >
                    <CalendarSearch />
                  </Button>
                </div>
                <DataTableSap
                  columns={ColumnsComponentSap}
                  data={mockDAta.value.length ? mockDAta.value : []}
                />
              </CardContent>
            </Card>
            <Card className="border-2 border-lime-500 flex flex-col shadow-md ">
              <CardHeader>
                <CardDescription>Lista das Ordens de Fabrico</CardDescription>
              </CardHeader>
              <CardContent>
                <DataTable
                  columns={ColumnsComponent}
                  data={
                    reatores.data?.reator.length ? reatores.data?.reator : []
                  }
                />
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  );
};

export default page;
/*
                <DataTableSap
                  columns={ColumnsComponentSap}
                  data={
                    ordensSAP.data?.value.length ? ordensSAP.data.value : []
                  }
                />
*/
const mockDAta = {
  "odata.metadata":
    "http://egiquim-sap:50001/b1s/v1/$metadata#ProductionOrders",
  value: [
    {
      AbsoluteEntry: 161641,
      DocumentNumber: 23005419,
      Series: 1239,
      ItemNo: "TSG 410/10",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 10.0,
      CompletedQuantity: 0.0,
      RejectedQuantity: 0.0,
      PostingDate: "2023-12-31T00:00:00Z",
      DueDate: "2023-12-31T00:00:00Z",
      ProductionOrderOriginEntry: 31566,
      ProductionOrderOriginNumber: 202400002,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 1,
      Remarks: null,
      ClosingDate: null,
      ReleaseDate: "2024-02-14T00:00:00Z",
      CustomerCode: "C00034",
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - TSG 410/10",
      TransactionNumber: null,
      CreationDate: "2024-02-14T00:00:00Z",
      Printed: "tNO",
      DistributionRule: "",
      Project: "",
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2023-12-31T00:00:00Z",
      ProductDescription: "Hidrofugante Aquoso Super-10 L",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaManual",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161641,
          LineNumber: 0,
          ItemNo: "TSG 410",
          BaseQuantity: 10.0,
          PlannedQuantity: 100.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2023-12-31T00:00:00Z",
          EndDate: "2023-12-31T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Hidrofugante Aquoso Super",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161641,
          LineNumber: 1,
          ItemNo: "MP0207",
          BaseQuantity: 1.0,
          PlannedQuantity: 10.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 1,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2023-12-31T00:00:00Z",
          EndDate: "2023-12-31T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "EMBALAGENS 10 L OPACAS",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161641,
          LineNumber: 2,
          ItemNo: "0011",
          BaseQuantity: 0.05,
          PlannedQuantity: 0.5,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 2,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2023-12-31T00:00:00Z",
          EndDate: "2023-12-31T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Papel Autocolante Alto Brilho",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161641,
          LineNumber: 3,
          ItemNo: "TSTMP0278",
          BaseQuantity: 20.0,
          PlannedQuantity: 200.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 3,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2023-12-31T00:00:00Z",
          EndDate: "2023-12-31T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "TSTActicide LA 1209",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [],
    },
    {
      AbsoluteEntry: 161642,
      DocumentNumber: 23005420,
      Series: 1239,
      ItemNo: "TSG 410/10",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 1.0,
      CompletedQuantity: 1.0,
      RejectedQuantity: 0.0,
      PostingDate: "2023-12-31T00:00:00Z",
      DueDate: "2023-12-31T00:00:00Z",
      ProductionOrderOriginEntry: null,
      ProductionOrderOriginNumber: null,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 1,
      Remarks: "ccccc",
      ClosingDate: null,
      ReleaseDate: "2024-02-14T00:00:00Z",
      CustomerCode: null,
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - TSG 410/10",
      TransactionNumber: null,
      CreationDate: "2024-02-14T00:00:00Z",
      Printed: "tNO",
      DistributionRule: "",
      Project: "",
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2023-12-31T00:00:00Z",
      ProductDescription: "Hidrofugante Aquoso Super-10 L",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaManual",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161642,
          LineNumber: 0,
          ItemNo: "TSTMP0278",
          BaseQuantity: 20.0,
          PlannedQuantity: 20.0,
          IssuedQuantity: 20.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2023-12-31T00:00:00Z",
          EndDate: "2023-12-31T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "TSTActicide LA 1209",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [],
    },
    {
      AbsoluteEntry: 161643,
      DocumentNumber: 24000001,
      Series: 1303,
      ItemNo: "607",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 3000.0,
      CompletedQuantity: 0.0,
      RejectedQuantity: 0.0,
      PostingDate: "2024-02-20T00:00:00Z",
      DueDate: "2024-02-20T00:00:00Z",
      ProductionOrderOriginEntry: null,
      ProductionOrderOriginNumber: null,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 18,
      Remarks: null,
      ClosingDate: null,
      ReleaseDate: "2024-02-21T00:00:00Z",
      CustomerCode: null,
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - 607",
      TransactionNumber: null,
      CreationDate: "2024-02-20T00:00:00Z",
      Printed: "tNO",
      DistributionRule: null,
      Project: null,
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2024-02-20T00:00:00Z",
      ProductDescription: "Lava Tudo Limao",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaCalculated",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 0,
          ItemNo: "MP0027",
          BaseQuantity: 0.02,
          PlannedQuantity: 60.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "UFACID K",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 1,
          ItemNo: "MP0139",
          BaseQuantity: 0.006667,
          PlannedQuantity: 20.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 1,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "SODA CÁUSTICA A 32%",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 2,
          ItemNo: "MP0025",
          BaseQuantity: 0.001667,
          PlannedQuantity: 5.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 2,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Acticide MBS",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 3,
          ItemNo: "MP0082",
          BaseQuantity: 9.0e-6,
          PlannedQuantity: 0.027,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 3,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "CORANTE FLURESCEÍNA PROQUIDET C-126",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 4,
          ItemNo: "MP0080",
          BaseQuantity: 2.0e-6,
          PlannedQuantity: 0.005,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 4,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "CORANTE TARTARAZINA",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 5,
          ItemNo: "MP0053/E",
          BaseQuantity: 0.015,
          PlannedQuantity: 45.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 5,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "MXS IPOH 05-Alcool Etilico",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 6,
          ItemNo: "MP0023",
          BaseQuantity: 0.000333,
          PlannedQuantity: 1.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 6,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "ÁC. CÍTRICO BP88",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161643,
          LineNumber: 7,
          ItemNo: "MP0145",
          BaseQuantity: 0.007,
          PlannedQuantity: 21.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 7,
          DistributionRule: "",
          LocationCode: null,
          Project: "",
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-20T00:00:00Z",
          EndDate: "2024-02-20T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "ESSÊNCIA Citronal 193361",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [
        {
          DocEntry: 161643,
          LineNumber: 1,
          RefDocEntr: 76779,
          RefDocNum: 201310288,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2013-12-20T00:00:00Z",
          Remark: null,
        },
      ],
    },
    {
      AbsoluteEntry: 161644,
      DocumentNumber: 24000002,
      Series: 1303,
      ItemNo: "660/12x1L",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 1.0,
      CompletedQuantity: 0.0,
      RejectedQuantity: 0.0,
      PostingDate: "2024-02-21T00:00:00Z",
      DueDate: "2024-02-21T00:00:00Z",
      ProductionOrderOriginEntry: null,
      ProductionOrderOriginNumber: null,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 1,
      Remarks: null,
      ClosingDate: null,
      ReleaseDate: "2024-02-21T00:00:00Z",
      CustomerCode: null,
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - 660/12x1L",
      TransactionNumber: null,
      CreationDate: "2024-02-21T00:00:00Z",
      Printed: "tNO",
      DistributionRule: "",
      Project: "",
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2024-02-21T00:00:00Z",
      ProductDescription: "DETCLOR Limão - 1L",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaCalculated",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161644,
          LineNumber: 0,
          ItemNo: "660/1L",
          BaseQuantity: 1.0,
          PlannedQuantity: 1.0,
          IssuedQuantity: 1.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "DETCLOR Limão - 1L",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161644,
          LineNumber: 1,
          ItemNo: "10390498",
          BaseQuantity: 1.0,
          PlannedQuantity: 1.0,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 1,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Caixa 12 Garrafas 1L Alta",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161644,
          LineNumber: 2,
          ItemNo: "0011",
          BaseQuantity: 0.03,
          PlannedQuantity: 0.03,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 2,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Papel Autocolante Alto Brilho",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161644,
          LineNumber: 3,
          ItemNo: "TSTMP0278",
          BaseQuantity: 12.5,
          PlannedQuantity: 12.5,
          IssuedQuantity: 0.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 3,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "TSTActicide LA 1209",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [
        {
          DocEntry: 161644,
          LineNumber: 1,
          RefDocEntr: 161639,
          RefDocNum: 23005417,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2023-06-26T00:00:00Z",
          Remark: null,
        },
      ],
    },
    {
      AbsoluteEntry: 161645,
      DocumentNumber: 24000003,
      Series: 1303,
      ItemNo: "660/12x1L",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 5.0,
      CompletedQuantity: 5.0,
      RejectedQuantity: 0.0,
      PostingDate: "2024-02-21T00:00:00Z",
      DueDate: "2024-02-21T00:00:00Z",
      ProductionOrderOriginEntry: null,
      ProductionOrderOriginNumber: null,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 1,
      Remarks: null,
      ClosingDate: null,
      ReleaseDate: "2024-02-21T00:00:00Z",
      CustomerCode: null,
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - 660/12x1L",
      TransactionNumber: null,
      CreationDate: "2024-02-21T00:00:00Z",
      Printed: "tNO",
      DistributionRule: "",
      Project: "",
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2024-02-21T00:00:00Z",
      ProductDescription: "DETCLOR Limão - 1L",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaCalculated",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161645,
          LineNumber: 0,
          ItemNo: "660/1L",
          BaseQuantity: 1.0,
          PlannedQuantity: 5.0,
          IssuedQuantity: 5.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "DETCLOR Limão - 1L",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161645,
          LineNumber: 1,
          ItemNo: "10390498",
          BaseQuantity: 1.0,
          PlannedQuantity: 5.0,
          IssuedQuantity: 5.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 1,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Caixa 12 Garrafas 1L Alta",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161645,
          LineNumber: 2,
          ItemNo: "0011",
          BaseQuantity: 0.03,
          PlannedQuantity: 0.15,
          IssuedQuantity: 0.15,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 2,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Papel Autocolante Alto Brilho",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161645,
          LineNumber: 3,
          ItemNo: "TSTMP0278",
          BaseQuantity: 12.5,
          PlannedQuantity: 62.5,
          IssuedQuantity: 62.5,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 3,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "TSTActicide LA 1209",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [
        {
          DocEntry: 161645,
          LineNumber: 1,
          RefDocEntr: 161639,
          RefDocNum: 23005417,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2023-06-26T00:00:00Z",
          Remark: null,
        },
        {
          DocEntry: 161645,
          LineNumber: 2,
          RefDocEntr: 161644,
          RefDocNum: 24000002,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2024-02-21T00:00:00Z",
          Remark: null,
        },
      ],
    },
    {
      AbsoluteEntry: 161646,
      DocumentNumber: 24000004,
      Series: 1303,
      ItemNo: "660/12x1L",
      ProductionOrderStatus: "boposReleased",
      ProductionOrderType: "bopotStandard",
      PlannedQuantity: 5.0,
      CompletedQuantity: 3.0,
      RejectedQuantity: 0.0,
      PostingDate: "2024-02-21T00:00:00Z",
      DueDate: "2024-02-21T00:00:00Z",
      ProductionOrderOriginEntry: null,
      ProductionOrderOriginNumber: null,
      ProductionOrderOrigin: "bopooManual",
      UserSignature: 1,
      Remarks: null,
      ClosingDate: null,
      ReleaseDate: "2024-02-21T00:00:00Z",
      CustomerCode: null,
      Warehouse: "01",
      InventoryUOM: null,
      JournalRemarks: "Ordem de produção - 660/12x1L",
      TransactionNumber: null,
      CreationDate: "2024-02-21T00:00:00Z",
      Printed: "tNO",
      DistributionRule: "",
      Project: "",
      DistributionRule2: null,
      DistributionRule3: null,
      DistributionRule4: null,
      DistributionRule5: null,
      UoMEntry: -1,
      StartDate: "2024-02-21T00:00:00Z",
      ProductDescription: "DETCLOR Limão - 1L",
      Priority: 100,
      RoutingDateCalculation: "raOnStartDate",
      UpdateAllocation: "bouaCalculated",
      SAPPassport: null,
      AttachmentEntry: null,
      U_Prd_TmpMinMist: null,
      U_Prd_DensEsp: null,
      U_Prd_ViscEsp: null,
      U_Prd_ExtSecoEsp: null,
      U_Prd_phEsp: null,
      U_LoteFabrico: null,
      ProductionOrderLines: [
        {
          DocumentAbsoluteEntry: 161646,
          LineNumber: 0,
          ItemNo: "660/1L",
          BaseQuantity: 1.0,
          PlannedQuantity: 5.0,
          IssuedQuantity: 5.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 0,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "DETCLOR Limão - 1L",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161646,
          LineNumber: 1,
          ItemNo: "10390498",
          BaseQuantity: 1.0,
          PlannedQuantity: 5.0,
          IssuedQuantity: 3.0,
          ProductionOrderIssueType: "im_Backflush",
          Warehouse: "01",
          VisualOrder: 1,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Caixa 12 Garrafas 1L Alta",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161646,
          LineNumber: 2,
          ItemNo: "0011",
          BaseQuantity: 0.03,
          PlannedQuantity: 0.15,
          IssuedQuantity: 1.0,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 2,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "Papel Autocolante Alto Brilho",
          SerialNumbers: [],
          BatchNumbers: [],
        },
        {
          DocumentAbsoluteEntry: 161646,
          LineNumber: 3,
          ItemNo: "TSTMP0278",
          BaseQuantity: 12.5,
          PlannedQuantity: 62.5,
          IssuedQuantity: 62.5,
          ProductionOrderIssueType: "im_Manual",
          Warehouse: "01",
          VisualOrder: 3,
          DistributionRule: null,
          LocationCode: null,
          Project: null,
          DistributionRule2: null,
          DistributionRule3: null,
          DistributionRule4: null,
          DistributionRule5: null,
          UoMEntry: -1,
          UoMCode: -1,
          WipAccount: null,
          ItemType: "pit_Item",
          LineText: null,
          AdditionalQuantity: 0.0,
          ResourceAllocation: null,
          StartDate: "2024-02-21T00:00:00Z",
          EndDate: "2024-02-21T00:00:00Z",
          StageID: null,
          RequiredDays: 0.0,
          ItemName: "TSTActicide LA 1209",
          SerialNumbers: [],
          BatchNumbers: [],
        },
      ],
      ProductionOrdersSalesOrderLines: [],
      ProductionOrdersStages: [],
      ProductionOrdersDocumentReferences: [
        {
          DocEntry: 161646,
          LineNumber: 1,
          RefDocEntr: 161639,
          RefDocNum: 23005417,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2023-06-26T00:00:00Z",
          Remark: null,
        },
        {
          DocEntry: 161646,
          LineNumber: 2,
          RefDocEntr: 161644,
          RefDocNum: 24000002,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2024-02-21T00:00:00Z",
          Remark: null,
        },
        {
          DocEntry: 161646,
          LineNumber: 3,
          RefDocEntr: 161645,
          RefDocNum: 24000003,
          ExtDocNum: null,
          RefObjType: "rot_ProductionOrder",
          IssueDate: "2024-02-21T00:00:00Z",
          Remark: null,
        },
      ],
    },
  ],
};
