import axios from "axios";
import { useQuery } from "@tanstack/react-query";

interface DocumentLine {
  LineNum: number;
  ItemCode: string;
  ItemDescription: string;
  Quantity: number;
  ShipDate: string;
  Price: number;
  PriceAfterVAT: number;
  Currency: string;
  Rate: number;
  DiscountPercent: number;
  VendorNum: string;
  SerialNum: string | null;
  WarehouseCode: string;
  SalesPersonCode: number;
  CommisionPercent: number;
  TreeType: string;
  AccountCode: string;
  UseBaseUnits: string;
  SupplierCatNum: string;
  CostingCode: string;
  ProjectCode: string;
  BarCode: string;
  VatGroup: string;
  Height1: number;
  Hight1Unit: string | null;
  Height2: number;
  Height2Unit: string | null;
  Lengh1: number;
  Lengh1Unit: string | null;
  Lengh2: number;
  Lengh2Unit: string | null;
  Weight1: number;
  Weight1Unit: string | null;
  Weight2: number;
  Weight2Unit: string | null;
  Factor1: number;
  Factor2: number;
  Factor3: number;
  Factor4: number;
  BaseType: number;
  BaseEntry: number | null;
  BaseLine: number | null;
  Volume: number;
  VolumeUnit: number;
  Width1: number;
  Width1Unit: string | null;
  Width2: number;
  Width2Unit: string | null;
  Address: string;
  TaxCode: string | null;
  TaxType: string;
  TaxLiable: string;
  PickStatus: string;
  PickQuantity: number;
  PickListIdNumber: string | null;
  OriginalItem: string;
  BackOrder: string | null;
  FreeText: string | null;
  ShippingMethod: number;
  POTargetNum: string | null;
  POTargetEntry: string | null;
  POTargetRowNum: string | null;
  CorrectionInvoiceItem: string;
  CorrInvAmountToStock: number;
  CorrInvAmountToDiffAcct: number;
  AppliedTax: number;
  AppliedTaxFC: number;
  AppliedTaxSC: number;
  WTLiable: string;
  DeferredTax: string;
  EqualizationTaxPercent: number;
  TotalEqualizationTax: number;
  TotalEqualizationTaxFC: number;
  TotalEqualizationTaxSC: number;
  NetTaxAmount: number;
  NetTaxAmountFC: number;
  NetTaxAmountSC: number;
  MeasureUnit: string;
  UnitsOfMeasurment: number;
  LineTotal: number;
  TaxPercentagePerRow: number;
  TaxTotal: number;
  ConsumerSalesForecast: string;
  ExciseAmount: number;
  TaxPerUnit: number;
  TotalInclTax: number;
  CountryOrg: string | null;
  SWW: string;
  TransactionType: string | null;
  DistributeExpense: string;
  RowTotalFC: number;
  RowTotalSC: number;
  LastBuyInmPrice: number;
  LastBuyDistributeSumFc: number;
  LastBuyDistributeSumSc: number;
  LastBuyDistributeSum: number;
  StockDistributesumForeign: number;
  StockDistributesumSystem: number;
  StockDistributesum: number;
  StockInmPrice: number;
  PickStatusEx: string;
  TaxBeforeDPM: number | null;
  TaxBeforeDPMFC: number | null;
  TaxBeforeDPMSC: number | null;
  CFOPCode: string | null;
  CSTCode: string | null;
  Usage: string | null;
  TaxOnly: string;
  VisualOrder: number;
  BaseOpenQuantity: number;
  UnitPrice: number;
  LineStatus: string;
  PackageQuantity: number;
  Text: string | null;
  LineType: string;
  COGSCostingCode: string | null;
  COGSAccountCode: string | null;
  ChangeAssemlyBoMWarehouse: string;
  GrossBuyPrice: number;
  GrossBase: number | null;
  GrossProfitTotalBasePrice: number | null;
  CostingCode2: string | null;
  CostingCode3: string | null;
  CostingCode4: string | null;
  CostingCode5: string | null;
  ItemDetails: string | null;
  LocationCode: string | null;
  ActualDeliveryDate: string | null;
  RemainingOpenQuantity: number;
  OpenAmount: number;
  OpenAmountFC: number;
  OpenAmountSC: number;
  ExLineNo: string | null;
  RequiredDate: string | null;
  RequiredQuantity: number | null;
  COGSCostingCode2: string | null;
  COGSCostingCode3: string | null;
  COGSCostingCode4: string | null;
  COGSCostingCode5: string | null;
  CSTforIPI: string | null;
  CSTforPIS: string | null;
  CSTforCOFINS: string | null;
  CreditOriginCode: string | null;
  WithoutInventoryMovement: string;
  AgreementNo: string | null;
  AgreementRowNumber: string | null;
  ActualBaseEntry: number | null;
  ActualBaseLine: number | null;
  DocEntry: number;
  Surpluses: string | null;
  DefectAndBreakup: string | null;
  Shortages: string | null;
  ConsiderQuantity: string;
  PartialRetirement: string;
  RetirementQuantity: number | null;
  RetirementAPC: number | null;
  ThirdParty: string;
  PoNum: string | null;
  PoItmNum: string | null;
  ExpenseType: string | null;
  ReceiptNumber: string | null;
  ExpenseOperationType: string | null;
  FederalTaxID: string | null;
  GrossProfit: number;
  GrossProfitFC: number;
  GrossProfitSC: number;
  PriceSource: string;
  StgSeqNum: number | null;
  StgEntry: number | null;
  StgDesc: string | null;
  UoMEntry: number;
  UoMCode: string;
  InventoryQuantity: number;
  RemainingOpenInventoryQuantity: number;
  ParentLineNum: string | null;
  Incoterms: number;
  TransportMode: number;
  NatureOfTransaction: string | null;
  DestinationCountryForImport: string | null;
  DestinationRegionForImport: string | null;
  OriginCountryForExport: string | null;
  OriginRegionForExport: string | null;
  ItemType: string;
  ChangeInventoryQuantityIndependently: string;
  FreeOfChargeBP: string;
  SACEntry: string | null;
  HSNEntry: string | null;
  GrossPrice: number;
  GrossTotal: number;
  GrossTotalFC: number;
  GrossTotalSC: number;
  NCMCode: number;
  NVECode: string | null;
  IndEscala: string;
  CtrSealQty: number | null;
  CNJPMan: string | null;
  CESTCode: string | null;
  UFFiscalBenefitCode: string | null;
  ReverseCharge: string;
  ShipFromCode: string | null;
  ShipFromDescription: string | null;
  StandardItemIdentification: string | null;
  CommodityClassification: string | null;
  UnencumberedReason: string | null;
  CUSplit: string;
  ListNum: string | null;
  U_BNBpCtry: string;
  U_BNOriCtr: string;
  U_BNOriSta: string;
  U_BNDstSta: string | null;
  U_BNIncTrm: string | null;
  U_BNTAType: string;
  U_BNTrnMod: string | null;
  U_BNPort: string | null;
  U_BNCstPrc: string;
  U_BNTaxExt: string | null;
  U_BNBrdVal: number;
  U_BNComCod: string;
  U_BNSupUnt: string | null;
  U_BNSupMas: number;
  U_BNRelDec: string;
  U_BNDomFrg: string | null;
  U_Local_Entrega: string | null;
  U_Hora: string | null;
  LineTaxJurisdictions: any[];
  DocumentLineAdditionalExpenses: any[];
  WithholdingTaxLines: any[];
  SerialNumbers: any[];
  BatchNumbers: any[];
  DocumentLinesBinAllocations: any[];
}

export interface PurchaseOrder {
  "odata.metadata": string | null;
  "odata.etag": string;
  DocEntry: number;
  DocNum: number;
  DocType: string;
  HandWritten: string;
  Printed: string;
  DocDate: string;
  DocDueDate: string;
  CardCode: string;
  CardName: string;
  Address: string;
  NumAtCard: string | null;
  DocTotal: number;
  AttachmentEntry: string | null;
  DocCurrency: string;
  DocRate: number;
  Reference1: string;
  Reference2: string | null;
  Comments: string;
  JournalMemo: string;
  PaymentGroupCode: number;
  DocTime: string;
  SalesPersonCode: number;
  TransportationCode: number;
  Confirmed: string;
  ImportFileNum: string | null;
  SummeryType: string;
  ContactPersonCode: number;
  ShowSCN: string;
  Series: number;
  TaxDate: string;
  PartialSupply: string | null;
  DocObjectCode: string;
  ShipToCode: string | null;
  Indicator: string | null;
  FederalTaxID: string | null;
  DiscountPercent: number;
  PaymentReference: string | null;
  CreationDate: string;
  UpdateDate: string;
  FinancialPeriod: number;
  UserSign: number;
  TransNum: string | null;
  VatSum: number;
  VatSumSys: number;
  VatSumFc: number;
  NetProcedure: string;
  DocTotalFc: number;
  DocTotalSys: number;
  Form1099: string | null;
  Box1099: string | null;
  RevisionPo: string;
  RequriedDate: string | null;
  CancelDate: string | null;
  BlockDunning: string;
  Submitted: string;
  Segment: number;
  PickStatus: string;
  Pick: string;
  PaymentMethod: string;
  PaymentBlock: string;
  PaymentBlockEntry: string | null;
  CentralBankIndicator: string | null;
  MaximumCashDiscount: string;
  Reserve: string;
  Project: string | null;
  ExemptionValidityDateFrom: string | null;
  ExemptionValidityDateTo: string | null;
  WareHouseUpdateType: string;
  Rounding: string;
  ExternalCorrectedDocNum: string | null;
  InternalCorrectedDocNum: string | null;
  NextCorrectingDocument: string | null;
  DeferredTax: string;
  TaxExemptionLetterNum: string | null;
  WTApplied: number;
  WTAppliedFC: number;
  BillOfExchangeReserved: string;
  AgentCode: string | null;
  WTAppliedSC: number;
  TotalEqualizationTax: number;
  TotalEqualizationTaxFC: number;
  TotalEqualizationTaxSC: number;
  NumberOfInstallments: number;
  ApplyTaxOnFirstInstallment: string;
  WTNonSubjectAmount: number;
  WTNonSubjectAmountSC: number;
  WTNonSubjectAmountFC: number;
  WTExemptedAmount: number;
  WTExemptedAmountSC: number;
  WTExemptedAmountFC: number;
  BaseAmount: number;
  BaseAmountSC: number;
  BaseAmountFC: number;
  WTAmount: number;
  WTAmountSC: number;
  WTAmountFC: number;
  VatDate: string | null;
  DocumentsOwner: number;
  FolioPrefixString: string | null;
  FolioNumber: string | null;
  DocumentSubType: string;
  BPChannelCode: string | null;
  BPChannelContact: string | null;
  Address2: string;
  DocumentStatus: string;
  PeriodIndicator: string;
  PayToCode: string;
  ManualNumber: string | null;
  UseShpdGoodsAct: string;
  IsPayToBank: string;
  PayToBankCountry: string | null;
  PayToBankCode: string | null;
  PayToBankAccountNo: string | null;
  PayToBankBranch: string | null;
  BPL_IDAssignedToInvoice: string | null;
  DownPayment: number;
  ReserveInvoice: string;
  LanguageCode: number;
  TrackingNumber: string | null;
  PickRemark: string | null;
  ClosingDate: string | null;
  SequenceCode: string | null;
  SequenceSerial: string | null;
  SeriesString: string | null;
  SubSeriesString: string | null;
  SequenceModel: string;
  UseCorrectionVATGroup: string;
  TotalDiscount: number;
  DownPaymentAmount: number;
  DownPaymentPercentage: number;
  DownPaymentType: string;
  DownPaymentAmountSC: number;
  DownPaymentAmountFC: number;
  VatPercent: number;
  ServiceGrossProfitPercent: number | null;
  OpeningRemarks: string | null;
  ClosingRemarks: string | null;
  RoundingDiffAmount: number;
  RoundingDiffAmountFC: number;
  RoundingDiffAmountSC: number;
  Cancelled: string;
  SignatureInputMessage: string | null;
  SignatureDigest: string | null;
  CertificationNumber: string | null;
  PrivateKeyVersion: string | null;
  ControlAccount: string;
  InsuranceOperation347: string;
  ArchiveNonremovableSalesQuotation: string;
  GTSChecker: string | null;
  GTSPayee: string | null;
  ExtraMonth: number;
  ExtraDays: number | null;
  CashDiscountDateOffset: number;
  StartFrom: string;
  NTSApproved: string;
  ETaxWebSite: string | null;
  ETaxNumber: string | null;
  NTSApprovedNumber: string | null;
  EDocGenerationType: string;
  EDocSeries: string | null;
  EDocNum: string | null;
  EDocExportFormat: string | null;
  EDocStatus: string;
  EDocErrorCode: string | null;
  EDocErrorMessage: string | null;
  DownPaymentStatus: string;
  GroupSeries: string | null;
  GroupNumber: string | null;
  GroupHandWritten: string;
  ReopenOriginalDocument: string | null;
  ReopenManuallyClosedOrCanceledDocument: string | null;
  CreateOnlineQuotation: string;
  POSEquipmentNumber: string | null;
  POSManufacturerSerialNumber: string | null;
  POSCashierNumber: string | null;
  ApplyCurrentVATRatesForDownPaymentsToDraw: string;
  ClosingOption: string;
  SpecifiedClosingDate: string | null;
  OpenForLandedCosts: string;
  AuthorizationStatus: string;
  TotalDiscountFC: number;
  TotalDiscountSC: number;
  RelevantToGTS: string;
  BPLName: string | null;
  VATRegNum: string | null;
  AnnualInvoiceDeclarationReference: string | null;
  Supplier: string | null;
  Releaser: string | null;
  Receiver: string | null;
  BlanketAgreementNumber: string | null;
  IsAlteration: string;
  CancelStatus: string;
  AssetValueDate: string | null;
  DocumentDelivery: string;
  AuthorizationCode: string | null;
  StartDeliveryDate: string | null;
  StartDeliveryTime: string | null;
  EndDeliveryDate: string | null;
  EndDeliveryTime: string | null;
  VehiclePlate: string | null;
  ATDocumentType: string | null;
  ElecCommStatus: string | null;
  ElecCommMessage: string | null;
  ReuseDocumentNum: string;
  ReuseNotaFiscalNum: string;
  PrintSEPADirect: string;
  FiscalDocNum: string | null;
  POSDailySummaryNo: string | null;
  POSReceiptNo: string | null;
  PointOfIssueCode: string | null;
  Letter: string | null;
  FolioNumberFrom: string | null;
  FolioNumberTo: string | null;
  InterimType: string;
  RelatedType: number;
  RelatedEntry: string | null;
  SAPPassport: string | null;
  DocumentTaxID: string | null;
  DateOfReportingControlStatementVAT: string | null;
  ReportingSectionControlStatementVAT: string | null;
  ExcludeFromTaxReportControlStatementVAT: string;
  POS_CashRegister: string | null;
  UpdateTime: string;
  CreateQRCodeFrom: string | null;
  PriceMode: string | null;
  ShipFrom: string | null;
  CommissionTrade: string;
  CommissionTradeReturn: string;
  UseBillToAddrToDetermineTax: string | null;
  Cig: string | null;
  Cup: string | null;
  FatherCard: string | null;
  FatherType: string;
  ShipState: string | null;
  ShipPlace: string | null;
  CustOffice: string | null;
  FCI: string | null;
  AddLegIn: string | null;
  LegTextF: string | null;
  DANFELgTxt: string | null;
  DataVersion: number;
  LastPageFolioNumber: string | null;
  InventoryStatus: string;
  PlasticPackagingTaxRelevant: string;
  U_LocalCarga: string;
  U_DataCarga: string | null;
  U_HoraCarga: string | null;
  U_Matricula: string | null;
  U_LocalDescarga: string;
  U_DataDescarga: string | null;
  U_HoraDescarga: string | null;
  U_ObsInterna: string | null;
  U_EBR_SAFT_SNMAN: string | null;
  U_ATDocCode: string | null;
  U_LocalEntrega: string | null;
  U_HoraEntrega: string | null;
  Document_ApprovalRequests: any[];
  DocumentLines: DocumentLine[];
  ElectronicProtocols: any[];
  DocumentAdditionalExpenses: any[];
  WithholdingTaxDataWTXCollection: any[];
  WithholdingTaxDataCollection: any[];
  DocumentSpecialLines: any[];
  TaxExtension: any;
  AddressExtension: any;
  DocumentReferences: any[];
  "odata.nextLink": string | null;
}
/*
export interface ApiResponse {
  value: PurchaseOrder[];
}
*/
export const useFetchUmaOrdemCompraSAPData = (DocEntry: number) => {
  return useQuery({
    queryKey: ["ordemCompraSAP"],
    queryFn: async () => {
      const { data } = await axios.get(
        `http://egiquim-sap:50001/b1s/v1/PurchaseOrders(${DocEntry})`,
        { withCredentials: true }
      );
      return data as PurchaseOrder;
    },
    refetchInterval: 1000 * 60 * 5,
    refetchIntervalInBackground: true,
  });
};
